# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\79137\Pasha\6 semester\Coursework\GUI_test_code\GUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


'''class GraphicsShell(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.aaa = QtWidgets.QTabWidget(self.centralwidget)
        self.aaa.setGeometry(QtCore.QRect(20, 40, 661, 411))
        self.aaa.setObjectName("aaa")
        self.ConnectionParameters = QtWidgets.QWidget()
        self.ConnectionParameters.setObjectName("ConnectionParameters")
        self.layoutWidget = QtWidgets.QWidget(self.ConnectionParameters)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 250, 195, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.AutoConnectpushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.AutoConnectpushButton.setObjectName("AutoConnectpushButton")
        self.horizontalLayout.addWidget(self.AutoConnectpushButton)
        self.ConnectpushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.ConnectpushButton.setObjectName("ConnectpushButton")
        self.horizontalLayout.addWidget(self.ConnectpushButton)
        self.layoutWidget1 = QtWidgets.QWidget(self.ConnectionParameters)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 235, 227))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.BaudRateLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.BaudRateLabel.setObjectName("BaudRateLabel")
        self.gridLayout.addWidget(self.BaudRateLabel, 6, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 2)
        self.ComPortNumberlabel = QtWidgets.QLabel(self.layoutWidget1)
        self.ComPortNumberlabel.setObjectName("ComPortNumberlabel")
        self.gridLayout.addWidget(self.ComPortNumberlabel, 5, 0, 1, 3)
        self.COMPortcomboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.COMPortcomboBox.setObjectName("COMPortcomboBox")
        self.COMPortcomboBox.addItem("")
        self.COMPortcomboBox.addItem("")
        self.COMPortcomboBox.addItem("")
        self.COMPortcomboBox.addItem("")
        self.COMPortcomboBox.addItem("")
        self.COMPortcomboBox.addItem("")
        self.COMPortcomboBox.addItem("")
        self.gridLayout.addWidget(self.COMPortcomboBox, 5, 3, 1, 2)
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.StopBitscomboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.StopBitscomboBox.setObjectName("StopBitscomboBox")
        self.StopBitscomboBox.addItem("")
        self.StopBitscomboBox.addItem("")
        self.gridLayout.addWidget(self.StopBitscomboBox, 4, 3, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.BaudRatecomboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.BaudRatecomboBox.setObjectName("BaudRatecomboBox")
        self.BaudRatecomboBox.addItem("")
        self.BaudRatecomboBox.addItem("")
        self.BaudRatecomboBox.addItem("")
        self.gridLayout.addWidget(self.BaudRatecomboBox, 6, 3, 1, 2)
        self.ByteSizecomboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.ByteSizecomboBox.setObjectName("ByteSizecomboBox")
        self.ByteSizecomboBox.addItem("")
        self.ByteSizecomboBox.addItem("")
        self.gridLayout.addWidget(self.ByteSizecomboBox, 1, 3, 1, 2)
        self.ParitycomboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.ParitycomboBox.setObjectName("ParitycomboBox")
        self.ParitycomboBox.addItem("")
        self.ParitycomboBox.addItem("")
        self.ParitycomboBox.addItem("")
        self.gridLayout.addWidget(self.ParitycomboBox, 3, 3, 1, 2)
        self.ProtocolcomboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.ProtocolcomboBox.setObjectName("ProtocolcomboBox")
        self.ProtocolcomboBox.addItem("")
        self.ProtocolcomboBox.addItem("")
        self.gridLayout.addWidget(self.ProtocolcomboBox, 0, 3, 1, 2)
        self.aaa.addTab(self.ConnectionParameters, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setGeometry(QtCore.QRect(80, 100, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.aaa.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuConnection_Parameters = QtWidgets.QMenu(self.menubar)
        self.menuConnection_Parameters.setObjectName("menuConnection_Parameters")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuConnection_Parameters.addSeparator()
        self.menubar.addAction(self.menuConnection_Parameters.menuAction())

        self.retranslateUi(MainWindow)
        self.aaa.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AutoConnectpushButton.setText(_translate("MainWindow", "Auto-Connect"))
        self.ConnectpushButton.setText(_translate("MainWindow", "Connect"))
        self.BaudRateLabel.setText(_translate("MainWindow", "Baud Rate: "))
        self.label_6.setText(_translate("MainWindow", "Stop Bits:"))
        self.ComPortNumberlabel.setText(_translate("MainWindow", "COM Port Number:"))
        self.COMPortcomboBox.setItemText(0, _translate("MainWindow", "1"))
        self.COMPortcomboBox.setItemText(1, _translate("MainWindow", "2"))
        self.COMPortcomboBox.setItemText(2, _translate("MainWindow", "3"))
        self.COMPortcomboBox.setItemText(3, _translate("MainWindow", "4"))
        self.COMPortcomboBox.setItemText(4, _translate("MainWindow", "5"))
        self.COMPortcomboBox.setItemText(5, _translate("MainWindow", "6"))
        self.COMPortcomboBox.setItemText(6, _translate("MainWindow", "7"))
        self.label.setText(_translate("MainWindow", "Protocol:"))
        self.label_2.setText(_translate("MainWindow", "Byte size"))
        self.StopBitscomboBox.setItemText(0, _translate("MainWindow", "1"))
        self.StopBitscomboBox.setItemText(1, _translate("MainWindow", "2"))
        self.label_5.setText(_translate("MainWindow", "Parity:"))
        self.BaudRatecomboBox.setItemText(0, _translate("MainWindow", "1200"))
        self.BaudRatecomboBox.setItemText(1, _translate("MainWindow", "2400"))
        self.BaudRatecomboBox.setItemText(2, _translate("MainWindow", "3600"))
        self.ByteSizecomboBox.setItemText(0, _translate("MainWindow", "7"))
        self.ByteSizecomboBox.setItemText(1, _translate("MainWindow", "8"))
        self.ParitycomboBox.setItemText(0, _translate("MainWindow", "O"))
        self.ParitycomboBox.setItemText(1, _translate("MainWindow", "N"))
        self.ParitycomboBox.setItemText(2, _translate("MainWindow", "E"))
        self.ProtocolcomboBox.setItemText(0, _translate("MainWindow", "RTU"))
        self.ProtocolcomboBox.setItemText(1, _translate("MainWindow", "ASCII"))
        self.aaa.setTabText(self.aaa.indexOf(self.ConnectionParameters), _translate("MainWindow", "Connection Parameters"))
        self.pushButton.setText(_translate("MainWindow", "NewButton"))
        self.aaa.setTabText(self.aaa.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menuConnection_Parameters.setTitle(_translate("MainWindow", "Connection Parameters"))'''

class GraphicsShell(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.aaa = QtWidgets.QTabWidget(self.centralwidget)
        self.aaa.setGeometry(QtCore.QRect(20, 40, 661, 411))
        self.aaa.setObjectName("aaa")
        self.ConnectionParameters = QtWidgets.QWidget()
        self.ConnectionParameters.setObjectName("ConnectionParameters")
        self.layoutWidget = QtWidgets.QWidget(self.ConnectionParameters)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 250, 195, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.AutoConnectpushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.AutoConnectpushButton.setObjectName("AutoConnectpushButton")
        self.horizontalLayout.addWidget(self.AutoConnectpushButton)
        self.ConnectpushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.ConnectpushButton.setObjectName("ConnectpushButton")
        self.horizontalLayout.addWidget(self.ConnectpushButton)
        self.layoutWidget1 = QtWidgets.QWidget(self.ConnectionParameters)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 235, 227))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.BaudRateLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.BaudRateLabel.setObjectName("BaudRateLabel")
        self.gridLayout.addWidget(self.BaudRateLabel, 6, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 2)
        self.ComPortNumberlabel = QtWidgets.QLabel(self.layoutWidget1)
        self.ComPortNumberlabel.setObjectName("ComPortNumberlabel")
        self.gridLayout.addWidget(self.ComPortNumberlabel, 5, 0, 1, 3)
        self.COMPortcomboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.COMPortcomboBox.setObjectName("COMPortcomboBox")
        self.COMPortcomboBox.addItem("")
        self.COMPortcomboBox.setItemText(0, "")
        self.COMPortcomboBox.addItem("")
        self.COMPortcomboBox.addItem("")
        self.COMPortcomboBox.addItem("")
        self.COMPortcomboBox.addItem("")
        self.COMPortcomboBox.addItem("")
        self.COMPortcomboBox.addItem("")
        self.COMPortcomboBox.addItem("")
        self.gridLayout.addWidget(self.COMPortcomboBox, 5, 3, 1, 2)
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.StopBitscomboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.StopBitscomboBox.setObjectName("StopBitscomboBox")
        self.StopBitscomboBox.addItem("")
        self.StopBitscomboBox.setItemText(0, "")
        self.StopBitscomboBox.addItem("")
        self.StopBitscomboBox.addItem("")
        self.gridLayout.addWidget(self.StopBitscomboBox, 4, 3, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.BaudRatecomboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.BaudRatecomboBox.setObjectName("BaudRatecomboBox")
        self.BaudRatecomboBox.addItem("")
        self.BaudRatecomboBox.setItemText(0, "")
        self.BaudRatecomboBox.addItem("")
        self.BaudRatecomboBox.addItem("")
        self.BaudRatecomboBox.addItem("")
        self.gridLayout.addWidget(self.BaudRatecomboBox, 6, 3, 1, 2)
        self.ByteSizecomboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.ByteSizecomboBox.setObjectName("ByteSizecomboBox")
        self.ByteSizecomboBox.addItem("")
        self.ByteSizecomboBox.setItemText(0, "")
        self.ByteSizecomboBox.addItem("")
        self.ByteSizecomboBox.addItem("")
        self.gridLayout.addWidget(self.ByteSizecomboBox, 1, 3, 1, 2)
        self.ParitycomboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.ParitycomboBox.setObjectName("ParitycomboBox")
        self.ParitycomboBox.addItem("")
        self.ParitycomboBox.setItemText(0, "")
        self.ParitycomboBox.addItem("")
        self.ParitycomboBox.addItem("")
        self.ParitycomboBox.addItem("")
        self.gridLayout.addWidget(self.ParitycomboBox, 3, 3, 1, 2)
        self.ProtocolcomboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.ProtocolcomboBox.setObjectName("ProtocolcomboBox")
        self.ProtocolcomboBox.addItem("")
        self.ProtocolcomboBox.setItemText(0, "")
        self.ProtocolcomboBox.addItem("")
        self.ProtocolcomboBox.addItem("")
        self.gridLayout.addWidget(self.ProtocolcomboBox, 0, 3, 1, 2)
        self.aaa.addTab(self.ConnectionParameters, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setGeometry(QtCore.QRect(80, 100, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.aaa.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuConnection_Parameters = QtWidgets.QMenu(self.menubar)
        self.menuConnection_Parameters.setObjectName("menuConnection_Parameters")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuConnection_Parameters.addSeparator()
        self.menubar.addAction(self.menuConnection_Parameters.menuAction())

        self.retranslateUi(MainWindow)
        self.aaa.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AutoConnectpushButton.setText(_translate("MainWindow", "Auto-Connect"))
        self.ConnectpushButton.setText(_translate("MainWindow", "Connect"))
        self.BaudRateLabel.setText(_translate("MainWindow", "Baud Rate: "))
        self.label_6.setText(_translate("MainWindow", "Stop Bits:"))
        self.ComPortNumberlabel.setText(_translate("MainWindow", "COM Port Number:"))
        self.COMPortcomboBox.setItemText(1, _translate("MainWindow", "1"))
        self.COMPortcomboBox.setItemText(2, _translate("MainWindow", "2"))
        self.COMPortcomboBox.setItemText(3, _translate("MainWindow", "3"))
        self.COMPortcomboBox.setItemText(4, _translate("MainWindow", "4"))
        self.COMPortcomboBox.setItemText(5, _translate("MainWindow", "5"))
        self.COMPortcomboBox.setItemText(6, _translate("MainWindow", "6"))
        self.COMPortcomboBox.setItemText(7, _translate("MainWindow", "7"))
        self.label.setText(_translate("MainWindow", "Protocol:"))
        self.label_2.setText(_translate("MainWindow", "Byte size"))
        self.StopBitscomboBox.setItemText(1, _translate("MainWindow", "1"))
        self.StopBitscomboBox.setItemText(2, _translate("MainWindow", "2"))
        self.label_5.setText(_translate("MainWindow", "Parity:"))
        self.BaudRatecomboBox.setItemText(1, _translate("MainWindow", "1200"))
        self.BaudRatecomboBox.setItemText(2, _translate("MainWindow", "2400"))
        self.BaudRatecomboBox.setItemText(3, _translate("MainWindow", "3600"))
        self.ByteSizecomboBox.setItemText(1, _translate("MainWindow", "7"))
        self.ByteSizecomboBox.setItemText(2, _translate("MainWindow", "8"))
        self.ParitycomboBox.setItemText(1, _translate("MainWindow", "O"))
        self.ParitycomboBox.setItemText(2, _translate("MainWindow", "N"))
        self.ParitycomboBox.setItemText(3, _translate("MainWindow", "E"))
        self.ProtocolcomboBox.setItemText(1, _translate("MainWindow", "RTU"))
        self.ProtocolcomboBox.setItemText(2, _translate("MainWindow", "ASCII"))
        self.aaa.setTabText(self.aaa.indexOf(self.ConnectionParameters), _translate("MainWindow", "Connection Parameters"))
        self.pushButton.setText(_translate("MainWindow", "NewButton"))
        self.aaa.setTabText(self.aaa.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menuConnection_Parameters.setTitle(_translate("MainWindow", "Connection Parameters"))


